{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "93aa2f02-b571-4aa2-90ab-8c647f75ddc2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-25 20:12:21.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.610 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.610 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.627 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.656 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.666 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-25 20:12:21.680 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import numpy as np\n",
    "\n",
    "# -------------------------------\n",
    "# LOAD MODELS\n",
    "# -------------------------------\n",
    "stack_model = joblib.load(\"stack_model.pkl\")\n",
    "sem_model = joblib.load(\"sem_model.pkl\")\n",
    "\n",
    "# -------------------------------\n",
    "# PAGE CONFIG\n",
    "# -------------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Sales Performance & SEM Predictor\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# -------------------------------\n",
    "# TITLE\n",
    "# -------------------------------\n",
    "st.title(\"📊 Sales Performance Prediction System\")\n",
    "st.markdown(\"Predict sales performance using CRM & behavioral constructs using ML and SEM models.\")\n",
    "\n",
    "# -------------------------------\n",
    "# SIDEBAR INPUT\n",
    "# -------------------------------\n",
    "st.sidebar.header(\"Input Features\")\n",
    "\n",
    "def user_input():\n",
    "    # Adjust sliders to match the features used in your SEM model\n",
    "    data = {\n",
    "        \"Self_Efficacy\": st.sidebar.slider(\"Self Efficacy (SE)\", 1.0, 5.0, 3.0),\n",
    "        \"Playfulness\": st.sidebar.slider(\"Playfulness (P)\", 1.0, 5.0, 3.0),\n",
    "        \"Social_Norms\": st.sidebar.slider(\"Social Norms (SN)\", 1.0, 5.0, 3.0),\n",
    "        \"Voluntariness\": st.sidebar.slider(\"Voluntariness (VN)\", 1.0, 5.0, 3.0),\n",
    "        \"User_Involvement\": st.sidebar.slider(\"User Involvement (UI)\", 1.0, 5.0, 3.0),\n",
    "        \"User_Participation\": st.sidebar.slider(\"User Participation (UP)\", 1.0, 5.0, 3.0),\n",
    "        \"Management_Support\": st.sidebar.slider(\"Management Support (MS)\", 1.0, 5.0, 3.0),\n",
    "        \"Relative_Advantage\": st.sidebar.slider(\"Relative Advantage (RAD)\", 1.0, 5.0, 3.0),\n",
    "        \"Results_Demonstrability\": st.sidebar.slider(\"Results Demonstrability (RD)\", 1.0, 5.0, 3.0),\n",
    "        \"Image\": st.sidebar.slider(\"Image (I)\", 1.0, 5.0, 3.0),\n",
    "        \"Compatibility\": st.sidebar.slider(\"Compatibility (C)\", 1.0, 5.0, 3.0),\n",
    "        \"Professional_Fit\": st.sidebar.slider(\"Professional Fit (PF)\", 1.0, 5.0, 3.0),\n",
    "        \"Complexity\": st.sidebar.slider(\"Complexity (CLX)\", 1.0, 5.0, 3.0),\n",
    "        \"Job_Fit\": st.sidebar.slider(\"Job Fit (JF)\", 1.0, 5.0, 3.0),\n",
    "        \"Visibility\": st.sidebar.slider(\"Visibility (V)\", 1.0, 5.0, 3.0),\n",
    "        \"CRM\": st.sidebar.slider(\"CRM\", 1.0, 5.0, 3.0)\n",
    "    }\n",
    "\n",
    "    return pd.DataFrame([data])\n",
    "\n",
    "input_df = user_input()\n",
    "\n",
    "# -------------------------------\n",
    "# DISPLAY INPUT\n",
    "# -------------------------------\n",
    "st.subheader(\"📥 Input Data\")\n",
    "st.write(input_df)\n",
    "\n",
    "# -------------------------------\n",
    "# PREDICTIONS\n",
    "# -------------------------------\n",
    "if st.button(\"Predict\"):\n",
    "\n",
    "    # -------- Stacking ML Model --------\n",
    "    st.subheader(\"🟢 Stacking Model Prediction\")\n",
    "    prediction = stack_model.predict(input_df)\n",
    "    if hasattr(stack_model, \"predict_proba\"):\n",
    "        prediction_proba = stack_model.predict_proba(input_df)\n",
    "        confidence = np.max(prediction_proba)\n",
    "    else:\n",
    "        confidence = \"N/A\"\n",
    "\n",
    "    st.success(f\"Predicted Class: {prediction[0]}\")\n",
    "    st.info(f\"Confidence: {confidence}\")\n",
    "\n",
    "    if hasattr(stack_model, \"feature_importances_\"):\n",
    "        st.subheader(\"Feature Importance (Stacking Model)\")\n",
    "        st.bar_chart(stack_model.feature_importances_)\n",
    "\n",
    "    # -------- SEM Model --------\n",
    "    st.subheader(\"🔵 SEM Model Prediction / Output\")\n",
    "    # SEM models usually have a method to calculate latent variable scores or predicted endogenous variables\n",
    "    try:\n",
    "        sem_scores = sem_model.predict(input_df)  # Adjust if your SEM library uses different API\n",
    "        st.write(sem_scores)\n",
    "    except:\n",
    "        st.warning(\"SEM model prediction requires proper SEM input. Adjust as needed.\")\n",
    "\n",
    "# -------------------------------\n",
    "# FOOTER\n",
    "# -------------------------------\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"Models: Stacking Classifier & SEM | Built for CRM & Sales Analysis\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2191c93-9774-4b90-b139-ce0375e7666d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
